services:
  distributedfileprocessor.api:
    image: distributedfileprocessorapi
    build:
      context: .
      dockerfile: src/DistributedFileProcessor.API/Dockerfile

  distributedfileprocessor.worker:
    image: distributedfileprocessorworker
    build:
      context: .
      dockerfile: src/DistributedFileProcessor.Worker/Dockerfile

