services:
  distributedfileprocessor.api:
    image: ${DOCKER_REGISTRY-}distributedfileprocessorapi
    build:
      context: .
      dockerfile: src/DistributedFileProcessor.API/Dockerfile

  distributedfileprocessor.worker:
    image: ${DOCKER_REGISTRY-}distributedfileprocessorworker
    build:
      context: .
      dockerfile: src/DistributedFileProcessor.Worker/Dockerfile

