name: Performance & Stress Testing (k6)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["LocalStack Deployment (Dev)"]
    types:
      - completed

env:
  BASE_URL: "http://127.0.0.1:8080"
  K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
  K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
  K6_CLOUD_STACK_ID: ${{ secrets.K6_CLOUD_STACK_ID }}

jobs:
  k6-load-test:
    name: Execute k6 Load Test with Grafana Cloud Streaming
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Start Environment (Infra + Services) 🐳
        run: |
          docker compose \
            -f docker-compose.yml \
            -f docker-compose.override.yml \
            up -d --build

      - name: Wait for Services Initialization ⏳
        run: sleep 40

      - name: Warm-up API (Bypass .NET Cold Start) ⚡
        run: |
          echo "Warming up the API..."
          curl -sS -o /dev/null -w "HTTP Status: %{http_code}\n" -X POST "${{ env.BASE_URL }}/api/documents/upload" \
            -H "Content-Type: application/json" \
            -d '{"fileName": "warmup-dummy-request.csv"}'
          echo "Warm-up complete!"

      - name: Generate CSV Payload 📄
        run: docker compose run --rm csv-generator

      - name: Run k6 Load Test & Stream to Cloud 📊
        run: |
          docker run --rm \
            --network host \
            -e BASE_URL="$BASE_URL" \
            -e K6_CLOUD_TOKEN="$K6_CLOUD_TOKEN" \
            -e K6_CLOUD_PROJECT_ID="$K6_CLOUD_PROJECT_ID" \
            -e K6_CLOUD_STACK_ID="$K6_CLOUD_STACK_ID" \
            -v ${{ github.workspace }}/k6:/scripts \
            -v ${{ github.workspace }}/tools/output:/data \
            grafana/k6:latest cloud run --local-execution /scripts/upload-documents-stress.js

      - name: Show Logs on Failure 🚨
        if: failure()
        run: |
          docker compose ps
          docker compose logs api
          docker compose logs localstack

      - name: Tear Down Environment 🧹
        if: always()
        run: docker compose down -v
